import { Project, TaskItem } from "../types";

export interface StaleTaskAnalysis {
  staleCount: number;
  staleTasks: TaskItem[];
  recommendation: string;
}

export interface ClientStatusReport {
  projectId: string;
  projectName: string;
  generatedAt: string;
  overallProgress: number;
  currentActivePhase: string;
  completedPhasesCount: number;
  totalPhasesCount: number;
  markdownReport: string;
}

/**
 * Scans tasks to identify stale items (tasks open with no updates for >3 days or past due)
 */
export function analyzeTaskStaleness(tasks: TaskItem[]): StaleTaskAnalysis {
  const now = new Date();
  const THREE_DAYS_MS = 3 * 24 * 60 * 60 * 1000;

  const staleTasks = tasks.filter((task) => {
    if (task.status === "Closed") return false;
    
    // Check explicit flag
    if (task.staleAlert) return true;

    // Check last activity date
    if (task.lastActivityDate) {
      const lastActive = new Date(task.lastActivityDate);
      if (now.getTime() - lastActive.getTime() > THREE_DAYS_MS) {
        return true;
      }
    }

    // Check due date
    if (task.dueDate) {
      const due = new Date(task.dueDate);
      if (due < now) {
        return true;
      }
    }

    return false;
  });

  let recommendation = "All tasks are moving on schedule.";
  if (staleTasks.length > 0) {
    recommendation = `Attention: ${staleTasks.length} task(s) appear stale or overdue. We recommend notifying assigned department owners (${Array.from(
      new Set(staleTasks.map((t) => t.departmentAlias || "unassigned"))
    ).join(", ")}).`;
  }

  return {
    staleCount: staleTasks.length,
    staleTasks,
    recommendation,
  };
}

/**
 * Auto-generates an AI executive status report for clients based on SOP phase progress
 */
export function generateAIClientStatusReport(
  project: Project,
  projectTasks: TaskItem[]
): ClientStatusReport {
  const totalTasks = projectTasks.length || project.totalTasksCount || 1;
  const completedTasks = projectTasks.filter((t) => t.status === "Closed").length;
  const overallProgress = Math.round((completedTasks / totalTasks) * 100) || project.progressPercent;

  // Group tasks by phase
  const phaseMap = new Map<string, { total: number; closed: number }>();
  projectTasks.forEach((task) => {
    const pName = task.phaseName || "General Tasks";
    const current = phaseMap.get(pName) || { total: 0, closed: 0 };
    current.total += 1;
    if (task.status === "Closed") current.closed += 1;
    phaseMap.set(pName, current);
  });

  let currentActivePhase = "Phase 1: Kickoff & Requirement Gathering";
  const phaseSummaries: string[] = [];

  phaseMap.forEach((stats, phaseName) => {
    const pct = Math.round((stats.closed / stats.total) * 100);
    let statusIcon = "⏳ In Progress";
    if (pct === 100) {
      statusIcon = "✅ Completed";
    } else if (pct === 0) {
      statusIcon = "📅 Upcoming";
    } else {
      currentActivePhase = phaseName;
    }
    phaseSummaries.push(`- **${phaseName}**: ${pct}% completed (${stats.closed}/${stats.total} tasks) — *${statusIcon}*`);
  });

  const generatedAt = new Date().toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });

  const markdownReport = `### 📊 AI Client Status Update: ${project.name}
**Date:** ${generatedAt}  
**Project Key:** \`${project.id}\`  
**Overall Completion:** **${overallProgress}%**  
**Current Milestone Focus:** ${currentActivePhase}  

---

#### 📌 Phase Progress Breakdown
${phaseSummaries.length > 0 ? phaseSummaries.join("\n") : "- *7-Phase SOP Template active. Progress tracked in real-time.*"}

---

#### 🚀 Key Highlights & Next Steps
- **Completed Deliverables:** ${completedTasks} of ${totalTasks} sub-deliverables verified.
- **Active Focus:** Work is actively progressing in **${currentActivePhase}**.
- **Target Deadline:** Target completion date set for **${project.deadline || "TBD"}**.

*Report automatically generated by EagleEye WinOS Project SOP Engine.*`;

  return {
    projectId: project.id,
    projectName: project.name,
    generatedAt,
    overallProgress,
    currentActivePhase,
    completedPhasesCount: project.completedPhasesCount,
    totalPhasesCount: project.totalPhasesCount || 7,
    markdownReport,
  };
}

/**
 * Helper to auto-assign department email aliases based on keywords in task titles
 */
export function inferDepartmentAlias(title: string): string {
  const lower = title.toLowerCase();
  if (lower.includes("seo") || lower.includes("meta") || lower.includes("keyword") || lower.includes("analytics")) {
    return "seo@";
  }
  if (lower.includes("design") || lower.includes("ux") || lower.includes("ui") || lower.includes("wireframe") || lower.includes("figma")) {
    return "design@";
  }
  if (lower.includes("dev") || lower.includes("code") || lower.includes("api") || lower.includes("build") || lower.includes("database")) {
    return "dev@";
  }
  if (lower.includes("qa") || lower.includes("test") || lower.includes("bug")) {
    return "qa@";
  }
  return "digitalproducts@";
}
