export const ROUTES = {
  home: "/",
  login: "/login",
  clientLogin: "/client/login",
  clientPortal: "/portal",
  dashboard: "/dashboard",
  dsm: "/dsm",
  dsmMy: "/dsm/my",
  dsmAll: "/dsm/all",
  dsmMember: (userId: string) => `/dsm/member/${userId}` as const,
  // The end-of-day DSR is now "Reporting" (UI + URLs). Keys keep the `dsr` prefix because the
  // DsrEntry model/feature folder are unchanged; old /dsr URLs redirect via next.config.ts.
  dsr: "/report",
  dsrMy: "/report/my",
  dsrManage: "/report/all",
  dsrMember: (userId: string) => `/report/member/${userId}` as const,
  notes: "/notes",
  calendar: "/calendar",
  zohoCalendar: "/calendar",
  blockers: "/blockers",
  support: "/support",
  needsHelp: "/needs-help",
  settingsUsers: "/settings/users",
  settingsUsersNew: "/settings/users/member/new",
  settingsUsersEdit: (userId: string) => `/settings/users/member/${userId}/edit` as const,
  settingsProfileAccess: "/settings/profile-access",
  pulseLeave: "/pulse/leave",
  pulseLeaveApply: "/pulse/leave/apply",
  pulseAttendance: "/pulse/attendance",
  pulseTeamAttendance: "/pulse/team-attendance",
  pulseRegularization: "/pulse/regularization",
  pulseReports: "/pulse/reports",
  pulseProfile: "/pulse/profile",
  restricted: "/restricted",
} as const;

export const PUBLIC_ROUTES: string[] = [ROUTES.login, ROUTES.clientLogin];
